/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.MenuController;
import javax.swing.JButton;
import javax.swing.JMenuBar;

/**
 *
 * @author HMS
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    
    private MenuController controller;
    public boolean AcessoAdmin = false;
    
    public MenuView() {
        initComponents();
        controller = new MenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEntrada = new javax.swing.JButton();
        jButtonReentrada = new javax.swing.JButton();
        jButtonCadastro = new javax.swing.JButton();
        bAdministrativo = new javax.swing.JButton();
        menuAdmin = new javax.swing.JMenuBar();
        aba_admin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(450, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonEntrada.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEntrada.setText("Entrada");
        jButtonEntrada.setToolTipText("");
        jButtonEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntradaActionPerformed(evt);
            }
        });

        jButtonReentrada.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReentrada.setText("Reentrada");
        jButtonReentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReentradaActionPerformed(evt);
            }
        });

        jButtonCadastro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastro.setText("Cadastro Saída");
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });

        bAdministrativo.setBackground(new java.awt.Color(255, 255, 255));
        bAdministrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.jpg"))); // NOI18N
        bAdministrativo.setText("Acessar administrativo");
        bAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdministrativoActionPerformed(evt);
            }
        });

        menuAdmin.setBackground(new java.awt.Color(255, 255, 255));
        menuAdmin.setName("menuAdmin"); // NOI18N

        aba_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.jpg"))); // NOI18N
        aba_admin.setText("Administrativo");
        aba_admin.setName("aba_admin"); // NOI18N
        aba_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aba_adminMouseClicked(evt);
            }
        });
        menuAdmin.add(aba_admin);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButtonEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButtonReentrada)
                .addGap(35, 35, 35)
                .addComponent(jButtonCadastro)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bAdministrativo)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEntrada)
                    .addComponent(jButtonReentrada)
                    .addComponent(jButtonCadastro))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        bAdministrativo.getAccessibleContext().setAccessibleName("bAdministrativo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntradaActionPerformed
        // TODO add your handling code here:       
        EntradaView telaEntrada = new EntradaView();
        telaEntrada.setVisible(true);
    }//GEN-LAST:event_jButtonEntradaActionPerformed

    private void jButtonReentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReentradaActionPerformed
        // TODO add your handling code here:
        ReentradaView telaReentrada = new ReentradaView();
        telaReentrada.setVisible(true);
    }//GEN-LAST:event_jButtonReentradaActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        // TODO add your handling code here:
        CadastroSaidaView telaCadastroSaida = new CadastroSaidaView();
        telaCadastroSaida.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void bAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdministrativoActionPerformed
           LoginAdminView dialog = new LoginAdminView(new javax.swing.JFrame(), true);
           dialog.setVisible(true);     
           AcessoAdmin = dialog.acesso;
           getMenuAdmin().setVisible(AcessoAdmin);
           getbAdministrativo().setVisible(!AcessoAdmin);
    }//GEN-LAST:event_bAdministrativoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         menuAdmin.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void aba_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aba_adminMouseClicked
          MenuAdminView dialog = new MenuAdminView(new javax.swing.JFrame(), true);
          dialog.setVisible(true); 
    }//GEN-LAST:event_aba_adminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    public JMenuBar getMenuAdmin() {
        return menuAdmin;
    }

    public void setMenuAdmin(JMenuBar menuAdmin) {
        this.menuAdmin = menuAdmin;
    }

    public JButton getbAdministrativo() {
        return bAdministrativo;
    }

    public void setbAdministrativo(JButton bAdministrativo) {
        this.bAdministrativo = bAdministrativo;
    } 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aba_admin;
    private javax.swing.JButton bAdministrativo;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonEntrada;
    private javax.swing.JButton jButtonReentrada;
    private javax.swing.JMenuBar menuAdmin;
    // End of variables declaration//GEN-END:variables
}
